# Generated by Django 4.1.3 on 2022-12-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_by', models.CharField(max_length=255)),
                ('issue_time', models.DateTimeField(auto_now_add=True)),
                ('issue', models.TextField()),
                ('importance', models.CharField(max_length=255)),
                ('status', models.BooleanField(null=True)),
            ],
            options={
                'ordering': ['issue_time'],
            },
        ),
    ]
